import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import './globals.css';


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  sidenav
}: Readonly<{
  children: React.ReactNode,
  sidenav: React.ReactNode,
}>) {
  return (
    <html lang="en">
      <body>
      <Link href="/">Home</Link>
        <span className="sidenav">
          <h3>Side Nav</h3>
          {sidenav}
        </span>
        <span>
          {children}
        </span>
        
        </body>
    </html>
  );
}
